name: Daily FX Rate Fetching Workflow

on:
  schedule:
    - cron: '0 18 * * *' #Scheduled daily on 18:00 UTC (around 20:00 or 21:00 Greece time depending on season)
  workflow_dispatch:     #To allow manual trigerring of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python fetch_currency_rates.py
        env:
          CONNECTION_STRING: ${{secrets.CONNECTION_STRING}}
